name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GOPRIVATE: https://github.com/RafayLabs

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.TOKEN }}:x-oauth-basic@github.com/RafayLabs".insteadOf "https://github.com/RafayLabs"

      - name: Test all
        run: go test -v ./...

  # golangci:
  #   strategy:
  #     matrix:
  #       go-version: [1.17.x]
  #       os: [ubuntu-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: ${{ matrix.go-version }}

  #     - name: Granting private modules access
  #       run: |
  #         git config --global url."https://${{ secrets.TOKEN }}:x-oauth-basic@github.com/RafayLabs".insteadOf "https://github.com/RafayLabs"

  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         version: v1.44.2
